user_password: ENC[AES256_GCM,data:yTgc2w==,iv:LFW64jx9AImvnlo4q2l9mGfFNwXCfjj6K07pPRTWCKk=,tag:RTOe6wfZnrBo0PIRWuO29w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qpw5h5sqc28rak35eehkqsc600nj5puhqduzmjuypmgkt7ylr58skafa6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZVlXa1E4SERJOXhnQlB4
            c1UxYU9GbERNaEMwaGFCZ3JqNW5rZDVEc1JFCjVmTUZ0Y2ZxR0k3RWROVGU2aEhR
            WVExeXhNWEtWR1VFeUg4dTF4YjRxY00KLS0tIHpIVGU1Zkt1UDNvOWR0SzZnSDZZ
            dU9xR1c5QUlsTGZ5UStxc0lyaTM4YlEKndiihSdS5GHRC3ZQc7rM8vX0yagaj/rO
            WJ6VcYADcV1Oq9uxUthkLPo3fVdfFLTZZiEjBlu/Tao5ZQVcm+j1jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T18:29:25Z"
    mac: ENC[AES256_GCM,data:WpoLZTU34ARU73bauTKZIS4VSNt5kngNWSsIyJLzthVMQi+joFtHp+4Enagt8OoIEXBnsB/cBvWvNZtGpGZAe19yLmD9koseoAhvFwt3frN5NatVdyh+ct9Hv5Qq8dUq4UU7dzNhae06XP5L3vpO/0spYrXAX0FbgIsy60mRT2Q=,iv:i31oo3JVbntrILP3QUC2/QR8P3MxtV6OcdvhTPdCJMQ=,tag:YAPJcYOmmNByIW9cNG+nbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
